version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:40"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
