/**
 * Canonical content format and a worked example for each DNS record type.
 *
 * Single source of truth: the Add Record dialog, the guided builders and any
 * other surface that needs to show "what should I type here?" read from this
 * table rather than carrying their own example strings.
 *
 * Conventions for every example below:
 * - domains use RFC 2606 reserved names (`example.com`, `.test`);
 * - IPv4 uses RFC 5737 documentation space (`192.0.2.0/24`);
 * - IPv6 uses RFC 3849 documentation space (`2001:db8::/32`);
 * - cryptographic payloads are illustrative but structurally correct — the
 *   right alphabet and the right length for the algorithm named beside them.
 *
 * Types whose canonical presentation format could not be stated with
 * confidence are deliberately absent rather than guessed; see
 * {@link RECORD_FORMAT_OMISSIONS}.
 */
import type { RecordType } from "@/types/dns";

export type RecordFormat = {
  /** Field order, using angle brackets for each field. */
  format: string;
  /** A single valid instance of that format. */
  example: string;
  /** One short clarifying sentence, shown in the help tooltip. */
  note?: string;
};

/**
 * Record types intentionally left without a format entry, with the reason.
 * Surfacing this keeps an unknown honest instead of shipping a wrong example.
 */
export const RECORD_FORMAT_OMISSIONS: Partial<Record<RecordType, string>> = {
  DCHID:
    "Listed as DCHID here but the IANA type is DHCID; its content is an opaque base64 digest generated by a DHCP server, so no hand-written example is meaningful.",
  HIP: "The Host Identity Protocol payload interleaves a hex Host Identity Tag with a base64 public key and optional rendezvous servers; the canonical presentation form could not be stated with confidence.",
};

export const RECORD_FORMATS: Partial<Record<RecordType, RecordFormat>> = {
  A: {
    format: "<IPv4 address>",
    example: "192.0.2.1",
    note: "A single dotted-quad IPv4 address. Publish one record per address.",
  },
  AAAA: {
    format: "<IPv6 address>",
    example: "2001:db8::1",
    note: "A single IPv6 address; the compressed :: form is fine.",
  },
  CNAME: {
    format: "<target hostname>",
    example: "www.example.com",
    note: "Aliases this whole name to the target. A name with a CNAME cannot hold any other record type.",
  },
  MX: {
    format: "<mail server hostname>",
    example: "mail.example.com",
    note: "Preference is entered in the separate Priority field; lower is tried first. The target must be a hostname with address records, never an alias or an IP.",
  },
  TXT: {
    format: '"<text>"',
    example: '"v=spf1 include:_spf.example.com ~all"',
    note: "Free text stored as quoted character-strings. Anything over 255 bytes is split into several strings that readers concatenate.",
  },
  SRV: {
    format: "<priority> <weight> <port> <target>",
    example: "10 5 5060 sip.example.com",
    note: "Lower priority is tried first; weight shares load between equal priorities. A target of . means the service is not offered here.",
  },
  NS: {
    format: "<nameserver hostname>",
    example: "ns1.example.com",
    note: "Delegates the name to that nameserver. Publish one record per nameserver.",
  },
  PTR: {
    format: "<hostname>",
    example: "host.example.com",
    note: "Maps a reverse-zone name back to a hostname; normally published in in-addr.arpa or ip6.arpa.",
  },
  CAA: {
    format: '<flags> <tag> "<value>"',
    example: '0 issue "letsencrypt.org"',
    note: "Flags are usually 0; 128 marks the tag critical. Tags are issue, issuewild or iodef. An empty value forbids issuance.",
  },
  DS: {
    format: "<key-tag> <algorithm> <digest-type> <digest>",
    example:
      "12345 13 2 49FD46E6C4B45C55D4AC69AC4C0B0B0F2D3E4F5A6B7C8D9E0F1A2B3C4D5E6F70",
    note: "Digest type 2 is SHA-256, so the digest is 64 hex characters. Algorithm 13 is ECDSA P-256. This record belongs in the parent zone.",
  },
  DNSKEY: {
    format: "<flags> <protocol> <algorithm> <public-key-base64>",
    example: "257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZJA4=",
    note: "Flags 257 is a key-signing key and 256 a zone-signing key. Protocol is always 3. Algorithm 15 is Ed25519.",
  },
  CDNSKEY: {
    format: "<flags> <protocol> <algorithm> <public-key-base64>",
    example: "257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZJA4=",
    note: "Same wire format as DNSKEY. It signals to the parent which key the DS record should be built from.",
  },
  NAPTR: {
    format:
      '<order> <preference> "<flags>" "<service>" "<regexp>" <replacement>',
    example: '100 10 "U" "E2U+sip" "!^.*$!sip:info@example.com!" .',
    note: "Lowest order is processed first. Regexp and replacement are mutually exclusive: use a regexp with replacement . , or a replacement with an empty regexp.",
  },
  SSHFP: {
    format: "<algorithm> <fingerprint-type> <fingerprint-hex>",
    example:
      "4 2 9DBA5E4F1B2C8A7D6E3F0A1B2C3D4E5F60718293A4B5C6D7E8F901A2B3C4D5E6",
    note: "Algorithm 4 is Ed25519 and fingerprint type 2 is SHA-256, giving 64 hex characters. Type 1 is SHA-1 and should not be used for new records.",
  },
  TLSA: {
    format: "<usage> <selector> <matching-type> <certificate-association-data>",
    example:
      "3 1 1 0B9FA5A59EED715C26C1020C711B4F6EC42D58B0015E14337A39DAD301C5AFC3",
    note: "Usage 3 pins the certificate directly, selector 1 hashes only the public key, matching type 1 is SHA-256. The owner name is _port._proto.host.",
  },
  SMIMEA: {
    format: "<usage> <selector> <matching-type> <certificate-association-data>",
    example:
      "3 1 1 0B9FA5A59EED715C26C1020C711B4F6EC42D58B0015E14337A39DAD301C5AFC3",
    note: "Same four fields as TLSA, but the owner name is the hashed mailbox local-part under _smimecert.",
  },
  OPENPGPKEY: {
    format: "<openpgp-public-key-base64>",
    example: "mDMEXEcE6RYJKwYBBAHaRw8BAQdArjWwk3FAqyiFbFBKT4TzXcVBqPTB3gmzlC8=",
    note: "The transferable public key in base64. The owner name is the hashed mailbox local-part under _openpgpkey.",
  },
  CERT: {
    format: "<type> <key-tag> <algorithm> <certificate-base64>",
    example: "1 0 0 MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A",
    note: "Type 1 is PKIX (an X.509 certificate); types 4, 6 and 8 hold a URL pointing at the certificate instead. Key tag 0 and algorithm 0 mean unspecified.",
  },
  HINFO: {
    format: '"<cpu>" "<os>"',
    example: '"AMD64" "LINUX"',
    note: "Two free-text character-strings, each up to 255 bytes. Legacy, and publishing it discloses host detail.",
  },
  LOC: {
    format:
      "<lat-d> <lat-m> <lat-s> <N|S> <lon-d> <lon-m> <lon-s> <E|W> <alt>m [size]m [hp]m [vp]m",
    example: "42 21 54 N 71 06 18 W -24m 30m",
    note: "Degrees, minutes and seconds with a hemisphere, then altitude in metres. Size, horizontal precision and vertical precision are optional diameters.",
  },
  SPF: {
    format: '"v=spf1 <mechanisms> <all-qualifier>all"',
    example: '"v=spf1 include:_spf.example.com ~all"',
    note: "The dedicated SPF record type is obsolete (RFC 7208); publish the same content as a TXT record instead.",
  },
  RP: {
    format: "<mailbox> <txt-domain>",
    example: "admin.example.com contact.example.com",
    note: "The mailbox writes @ as a dot, so admin.example.com means admin@example.com. A lone . means none in either field.",
  },
  DNAME: {
    format: "<target>",
    example: "new.example.com",
    note: "Rewrites everything below this name to the target. It does not redirect the name itself, which still needs its own records.",
  },
  AFSDB: {
    format: "<subtype> <hostname>",
    example: "1 afsdb.example.com",
    note: "Subtype 1 is an AFS cell database server, 2 a DCE authenticated-name server. The host must have address records.",
  },
  APL: {
    format: "[!]<address-family>:<address>/<prefix> ...",
    example: "1:192.0.2.0/24 !1:192.0.2.128/25",
    note: "Family 1 is IPv4 and 2 is IPv6; a leading ! negates the prefix. Experimental, with no standard meaning of its own.",
  },
  SOA: {
    format:
      "<primary-ns> <admin-mailbox> <serial> <refresh> <retry> <expire> <minimum>",
    example:
      "ns1.example.com admin.example.com 2026010101 7200 3600 1209600 3600",
    note: "The mailbox writes @ as a dot. Minimum is the negative-caching TTL, not a default record TTL. The serial must increase for secondaries to transfer.",
  },
  SVCB: {
    format: "<priority> <target> [key=value ...]",
    example: "1 svc.example.com. alpn=h2 port=8443",
    note: "Priority 0 is AliasMode and delegates the name to the target, ignoring all parameters. Any higher value is ServiceMode, where lower is preferred.",
  },
  HTTPS: {
    format: "<priority> <target> [key=value ...]",
    example: '1 . alpn="h3,h2" ipv4hint=192.0.2.1',
    note: "A target of . means this same name. Priority 0 is AliasMode. The ipv4hint and ipv6hint values are performance hints only, not authoritative addresses.",
  },
  URI: {
    format: '<priority> <weight> "<uri>"',
    example: '10 1 "https://www.example.com/"',
    note: "Lower priority is preferred, weight shares load between equal priorities. Looked up under _service._proto names, like SRV.",
  },
  IPSECKEY: {
    format:
      "<precedence> <gateway-type> <algorithm> <gateway> <public-key-base64>",
    example:
      "10 1 2 192.0.2.38 AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ==",
    note: "Gateway type 1 is an IPv4 gateway, 2 IPv6, 3 a domain name, 0 none. Algorithm 2 is RSA. Lower precedence is preferred.",
  },
  NSEC: {
    format: "<next-domain-name> <record-types>",
    example: "host.example.com A MX RRSIG NSEC",
    note: "Normally generated by the zone signer rather than written by hand; it proves which names and types do not exist.",
  },
  RRSIG: {
    format:
      "<type-covered> <algorithm> <labels> <original-ttl> <expiration> <inception> <key-tag> <signer> <signature-base64>",
    example:
      "A 13 2 3600 20260401000000 20260301000000 12345 example.com. AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ==",
    note: "Normally generated by the zone signer rather than written by hand. Timestamps are YYYYMMDDHHMMSS in UTC.",
  },
  ALIAS: {
    format: "<target hostname>",
    example: "www.example.com",
    note: "A provider-specific apex alias: the provider resolves the target and serves its addresses here. Behaviour varies by provider.",
  },
  ANAME: {
    format: "<target hostname>",
    example: "www.example.com",
    note: "A provider-specific apex alias: the provider resolves the target and serves its addresses here. Behaviour varies by provider.",
  },
};

/** Look up the format entry for a record type, if one is known. */
export function getRecordFormat(type: string | undefined) {
  if (!type) return undefined;
  return RECORD_FORMATS[type as RecordType];
}
