/**
 * Canonical content format and a worked example for each DNS record type.
 *
 * Single source of truth: the Add Record dialog, the guided builders and any
 * other surface that needs to show "what should I type here?" read from this
 * table rather than carrying their own example strings.
 *
 * Conventions for every example below:
 * - domains use RFC 2606 reserved names (`example.com`, `.test`);
 * - IPv4 uses RFC 5737 documentation space (`192.0.2.0/24`);
 * - IPv6 uses RFC 3849 documentation space (`2001:db8::/32`);
 * - cryptographic payloads are illustrative but structurally correct — the
 *   right alphabet and the right length for the algorithm named beside them.
 *
 * Types whose canonical presentation format could not be stated with
 * confidence are deliberately absent rather than guessed; see
 * {@link RECORD_FORMAT_OMISSIONS}.
 */
import type { RecordType } from "@/types/dns";

export type RecordFormat = {
  /** Field order, using angle brackets for each field. */
  format: string;
  /** A single valid instance of that format. */
  example: string;
  /** One short clarifying sentence, shown in the help tooltip. */
  note?: string;
};

/**
 * Record types intentionally left without a format entry, with the reason.
 * Surfacing this keeps an unknown honest instead of shipping a wrong example.
 */
export const RECORD_FORMAT_OMISSIONS: Partial<Record<RecordType, string>> = {
  DCHID:
    "Listed as DCHID here but the IANA type is DHCID; its content is an opaque base64 digest generated by a DHCP server, so no hand-written example is meaningful.",
  HIP: "The Host Identity Protocol payload interleaves a hex Host Identity Tag with a base64 public key and optional rendezvous servers; the canonical presentation form could not be stated with confidence.",
};

export const RECORD_FORMATS: Partial<Record<RecordType, RecordFormat>> = {
  A: {
    format: "<IPv4 address>",
    example: "192.0.2.1",
    note: "A single dotted-quad IPv4 address. Publish one record per address.",
  },
  AAAA: {
    format: "<IPv6 address>",
    example: "2001:db8::1",
    note: "A single IPv6 address; the compressed :: form is fine.",
  },
  CNAME: {
    format: "<target hostname>",
    example: "www.example.com",
    note: "Aliases this whole name to the target. A name with a CNAME cannot hold any other record type.",
  },
  MX: {
    format: "<mail server hostname>",
    example: "mail.example.com",
    note: "Preference is entered in the separate Priority field; lower is tried first. The target must be a hostname with address records, never an alias or an IP.",
  },
  TXT: {
    format: '"<text>"',
    example: '"v=spf1 include:_spf.example.com ~all"',
    note: "Free text stored as quoted character-strings. Anything over 255 bytes is split into several strings that readers concatenate.",
  },
  SRV: {
    format: "<priority> <weight> <port> <target>",
    example: "10 5 5060 sip.example.com",
    note: "Lower priority is tried first; weight shares load between equal priorities. A target of . means the service is not offered here.",
  },
  NS: {
    format: "<nameserver hostname>",
    example: "ns1.example.com",
    note: "Delegates the name to that nameserver. Publish one record per nameserver.",
  },
  PTR: {
    format: "<hostname>",
    example: "host.example.com",
    note: "Maps a reverse-zone name back to a hostname; normally published in in-addr.arpa or ip6.arpa.",
  },
  CAA: {
    format: '<flags> <tag> "<value>"',
    example: '0 issue "letsencrypt.org"',
    note: "Flags are usually 0; 128 marks the tag critical. Tags are issue, issuewild or iodef. An empty value forbids issuance.",
  },
  DS: {
    format: "<key-tag> <algorithm> <digest-type> <digest>",
    example:
      "12345 13 2 49FD46E6C4B45C55D4AC69AC4C0B0B0F2D3E4F5A6B7C8D9E0F1A2B3C4D5E6F70",
    note: "Digest type 2 is SHA-256, so the digest is 64 hex characters. Algorithm 13 is ECDSA P-256. This record belongs in the parent zone.",
  },
  DNSKEY: {
    format: "<flags> <protocol> <algorithm> <public-key-base64>",
    example: "257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZJA4=",
    note: "Flags 257 is a key-signing key and 256 a zone-signing key. Protocol is always 3. Algorithm 15 is Ed25519.",
  },
  CDNSKEY: {
    format: "<flags> <protocol> <algorithm> <public-key-base64>",
    example: "257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZJA4=",
    note: "Same wire format as DNSKEY. It signals to the parent which key the DS record should be built from.",
  },
  NAPTR: {
    format:
      '<order> <preference> "<flags>" "<service>" "<regexp>" <replacement>',
    example: '100 10 "U" "E2U+sip" "!^.*$!sip:info@example.com!" .',
    note: "Lowest order is processed first. Regexp and replacement are mutually exclusive: use a regexp with replacement . , or a replacement with an empty regexp.",
  },
  SSHFP: {
    format: "<algorithm> <fingerprint-type> <fingerprint-hex>",
    example:
      "4 2 9DBA5E4F1B2C8A7D6E3F0A1B2C3D4E5F60718293A4B5C6D7E8F901A2B3C4D5E6",
    note: "Algorithm 4 is Ed25519 and fingerprint type 2 is SHA-256, giving 64 hex characters. Type 1 is SHA-1 and should not be used for new records.",
  },
  TLSA: {
    format: "<usage> <selector> <matching-type> <certificate-association-data>",
    example:
      "3 1 1 0B9FA5A59EED715C26C1020C711B4F6EC42D58B0015E14337A39DAD301C5AFC3",
    note: "Usage 3 pins the certificate directly, selector 1 hashes only the public key, matching type 1 is SHA-256. The owner name is _port._proto.host.",
  },
  SMIMEA: {
    format: "<usage> <selector> <matching-type> <certificate-association-data>",
    example:
      "3 1 1 0B9FA5A59EED715C26C1020C711B4F6EC42D58B0015E14337A39DAD301C5AFC3",
    note: "Same four fields as TLSA, but the owner name is the hashed mailbox local-part under _smimecert.",
  },
  OPENPGPKEY: {
    format: "<openpgp-public-key-base64>",
    example: "mDMEXEcE6RYJKwYBBAHaRw8BAQdArjWwk3FAqyiFbFBKT4TzXcVBqPTB3gmzlC8=",
    note: "The transferable public key in base64. The owner name is the hashed mailbox local-part under _openpgpkey.",
  },
  CERT: {
    format: "<type> <key-tag> <algorithm> <certificate-base64>",
    example: "1 0 0 MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A",
    note: "Type 1 is PKIX (an X.509 certificate); types 4, 6 and 8 hold a URL pointing at the certificate instead. Key tag 0 and algorithm 0 mean unspecified.",
  },
  HINFO: {
    format: '"<cpu>" "<os>"',
    example: '"AMD64" "LINUX"',
    note: "Two free-text character-strings, each up to 255 bytes. Legacy, and publishing it discloses host detail.",
  },
  LOC: {
    format:
      "<lat-d> <lat-m> <lat-s> <N|S> <lon-d> <lon-m> <lon-s> <E|W> <alt>m [size]m [hp]m [vp]m",
    example: "42 21 54 N 71 06 18 W -24m 30m",
    note: "Degrees, minutes and seconds with a hemisphere, then altitude in metres. Size, horizontal precision and vertical precision are optional diameters.",
  },
  SPF: {
    format: '"v=spf1 <mechanisms> <all-qualifier>all"',
    example: '"v=spf1 include:_spf.example.com ~all"',
    note: "The dedicated SPF record type is obsolete (RFC 7208); publish the same content as a TXT record instead.",
  },
  RP: {
    format: "<mailbox> <txt-domain>",
    example: "admin.example.com contact.example.com",
    note: "The mailbox writes @ as a dot, so admin.example.com means admin@example.com. A lone . means none in either field.",
  },
  DNAME: {
    format: "<target>",
    example: "new.example.com",
    note: "Rewrites everything below this name to the target. It does not redirect the name itself, which still needs its own records.",
  },
  AFSDB: {
    format: "<subtype> <hostname>",
    example: "1 afsdb.example.com",
    note: "Subtype 1 is an AFS cell database server, 2 a DCE authenticated-name server. The host must have address records.",
  },
  APL: {
    format: "[!]<address-family>:<address>/<prefix> ...",
    example: "1:192.0.2.0/24 !1:192.0.2.128/25",
    note: "Family 1 is IPv4 and 2 is IPv6; a leading ! negates the prefix. Experimental, with no standard meaning of its own.",
  },
  SOA: {
    format:
      "<primary-ns> <admin-mailbox> <serial> <refresh> <retry> <expire> <minimum>",
    example:
      "ns1.example.com admin.example.com 2026010101 7200 3600 1209600 3600",
    note: "The mailbox writes @ as a dot. Minimum is the negative-caching TTL, not a default record TTL. The serial must increase for secondaries to transfer.",
  },
  SVCB: {
    format: "<priority> <target> [key=value ...]",
    example: "1 svc.example.com. alpn=h2 port=8443",
    note: "Priority 0 is AliasMode and delegates the name to the target, ignoring all parameters. Any higher value is ServiceMode, where lower is preferred.",
  },
  HTTPS: {
    format: "<priority> <target> [key=value ...]",
    example: '1 . alpn="h3,h2" ipv4hint=192.0.2.1',
    note: "A target of . means this same name. Priority 0 is AliasMode. The ipv4hint and ipv6hint values are performance hints only, not authoritative addresses.",
  },
  URI: {
    format: '<priority> <weight> "<uri>"',
    example: '10 1 "https://www.example.com/"',
    note: "Lower priority is preferred, weight shares load between equal priorities. Looked up under _service._proto names, like SRV.",
  },
  IPSECKEY: {
    format:
      "<precedence> <gateway-type> <algorithm> <gateway> <public-key-base64>",
    example:
      "10 1 2 192.0.2.38 AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ==",
    note: "Gateway type 1 is an IPv4 gateway, 2 IPv6, 3 a domain name, 0 none. Algorithm 2 is RSA. Lower precedence is preferred.",
  },
  NSEC: {
    format: "<next-domain-name> <record-types>",
    example: "host.example.com A MX RRSIG NSEC",
    note: "Normally generated by the zone signer rather than written by hand; it proves which names and types do not exist.",
  },
  RRSIG: {
    format:
      "<type-covered> <algorithm> <labels> <original-ttl> <expiration> <inception> <key-tag> <signer> <signature-base64>",
    example:
      "A 13 2 3600 20260401000000 20260301000000 12345 example.com. AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ==",
    note: "Normally generated by the zone signer rather than written by hand. Timestamps are YYYYMMDDHHMMSS in UTC.",
  },
  ALIAS: {
    format: "<target hostname>",
    example: "www.example.com",
    note: "A provider-specific apex alias: the provider resolves the target and serves its addresses here. Behaviour varies by provider.",
  },
  ANAME: {
    format: "<target hostname>",
    example: "www.example.com",
    note: "A provider-specific apex alias: the provider resolves the target and serves its addresses here. Behaviour varies by provider.",
  },
};

/** Look up the format entry for a record type, if one is known. */
export function getRecordFormat(type: string | undefined) {
  if (!type) return undefined;
  return RECORD_FORMATS[type as RecordType];
}

/** A specification a record type is defined by, linked to rfc-editor.org. */
export type RfcReference = {
  /** Canonical label, e.g. `RFC 1035`. */
  label: string;
  /** Section the type is defined in, when it is one section of a larger RFC. */
  section?: string;
  /** Absolute rfc-editor.org URL, anchored at `section` when there is one. */
  url: string;
  /** Why this reference matters, when it is not simply "defines the type". */
  note?: string;
};

/**
 * What a record type is *for*, in plain language, plus the specifications that
 * define it.
 *
 * This is a sibling of {@link RECORD_FORMATS} rather than part of it because
 * the two have different coverage on purpose: a type's job and its RFC are
 * knowable even where its presentation format was not stated with confidence
 * (see {@link RECORD_FORMAT_OMISSIONS}). Typing this as a total
 * `Record<RecordType, …>` makes the compiler the coverage test — a new entry in
 * `RECORD_TYPES` cannot ship without an explanation.
 *
 * Voice matches the guided builders: say what the record does, name the one
 * mistake people make with it, and stop. Where the semantics could not be
 * stated confidently the entry is deliberately short rather than padded.
 */
export type RecordDoc = {
  /** One or two sentences: what this record is for and its common pitfall. */
  purpose: string;
  /** Defining specs, most relevant first. Empty for non-standard types. */
  rfcs: RfcReference[];
};

/** Build an rfc-editor.org reference, anchored at a section when given. */
function rfc(number: number, section?: string, note?: string): RfcReference {
  const base = `https://www.rfc-editor.org/rfc/rfc${number}`;
  return {
    label: `RFC ${number}`,
    ...(section ? { section } : {}),
    url: section ? `${base}#section-${section}` : base,
    ...(note ? { note } : {}),
  };
}

export const RECORD_DOCS: Record<RecordType, RecordDoc> = {
  A: {
    purpose:
      "Publishes the IPv4 address a hostname resolves to. This is the record that points a name at a server; publish one record per address to hand out several.",
    rfcs: [rfc(1035, "3.4.1")],
  },
  AAAA: {
    purpose:
      "Publishes the IPv6 address a hostname resolves to — the IPv6 counterpart of an A record. A name can carry both, and clients pick per their own preference.",
    rfcs: [rfc(3596)],
  },
  CNAME: {
    purpose:
      "Declares that this name is an alias for another name; a resolver restarts the lookup at the target. Because the alias stands in for the whole name, a name with a CNAME cannot carry any other record — which is why it cannot be used at a zone apex.",
    rfcs: [rfc(1034, "3.6.2"), rfc(1035, "3.3.1")],
  },
  MX: {
    purpose:
      "Names a mail server that accepts email for this domain, with a preference number choosing between them. The target must be a hostname that has address records — never an IP address and never an alias.",
    rfcs: [
      rfc(1035, "3.3.9"),
      rfc(
        7505,
        undefined,
        "Defines the null MX, `0 .`, meaning this domain accepts no mail.",
      ),
    ],
  },
  TXT: {
    purpose:
      "Holds arbitrary text attached to a name. In practice it carries machine-readable policy: SPF, DKIM, DMARC and domain-ownership verification tokens all live here.",
    rfcs: [rfc(1035, "3.3.14")],
  },
  SRV: {
    purpose:
      "Advertises which host and port run a particular service, so clients need not assume a well-known port. The owner name encodes the service and protocol, as in `_sip._tcp.example.com`.",
    rfcs: [rfc(2782)],
  },
  NS: {
    purpose:
      "Delegates a zone, or a subdomain of it, to a nameserver. The NS set at the zone apex is what the parent zone points at, so it decides who is authoritative.",
    rfcs: [rfc(1035, "3.3.11")],
  },
  PTR: {
    purpose:
      "Maps an address back to a name — the reverse of an A or AAAA lookup. It lives in the `in-addr.arpa` or `ip6.arpa` reverse zone, which is normally controlled by whoever owns the IP range rather than by you.",
    rfcs: [rfc(1035, "3.3.12")],
  },
  CAA: {
    purpose:
      "Lists which certificate authorities may issue certificates for this domain. CAs are obliged to check it before issuing, so it guards against mis-issuance; resolvers themselves do nothing with it.",
    rfcs: [rfc(8659)],
  },
  DS: {
    purpose:
      "Delegation Signer: publishes a digest of the child zone's key-signing key in the parent zone, linking the two into the DNSSEC chain of trust. It belongs in the parent, so it is normally submitted through your registrar.",
    rfcs: [rfc(4034, "5")],
  },
  DNSKEY: {
    purpose:
      "Publishes a zone's DNSSEC public key so validators can check the RRSIG signatures made with the matching private key.",
    rfcs: [rfc(4034, "2")],
  },
  NAPTR: {
    purpose:
      "Rewrites a name into a URI or into another lookup by applying a regular expression, for chained service discovery — most familiarly ENUM, which maps a telephone number to a SIP address.",
    rfcs: [rfc(3403)],
  },
  SSHFP: {
    purpose:
      "Publishes a fingerprint of a host's SSH key so a client can verify the host on first connection instead of trusting it blindly. It is only worth trusting when the answer is DNSSEC-validated.",
    rfcs: [rfc(4255)],
  },
  TLSA: {
    purpose:
      "Ties a TLS certificate, or its issuer, to one host and port, so a client can reject a certificate that is valid to the public PKI but is not the one the domain owner published. This is DANE.",
    rfcs: [rfc(6698)],
  },
  HINFO: {
    purpose:
      "States the CPU and operating system of a host. Legacy: publishing it tells anyone asking exactly what the host runs.",
    rfcs: [rfc(1035, "3.3.2")],
  },
  LOC: {
    purpose:
      "Records a physical location — latitude, longitude and altitude — for a name. Informational; nothing routes on it.",
    rfcs: [rfc(1876)],
  },
  SPF: {
    purpose:
      "The retired dedicated record type for Sender Policy Framework. RFC 7208 removed it: publish the same policy as a TXT record instead, because that is the only place senders look.",
    rfcs: [
      rfc(7208, undefined, "Deprecates this type in favour of TXT."),
      rfc(4408, undefined, "The obsolete specification that introduced it."),
    ],
  },
  RP: {
    purpose:
      "Names a person responsible for a host: a mailbox, plus an optional pointer to a TXT record holding more detail. Informational.",
    rfcs: [rfc(1183)],
  },
  DNAME: {
    purpose:
      "Redirects an entire subtree: every name below this one is rewritten to the same name below the target. Unlike CNAME it does not redirect the name itself, which still needs its own records.",
    rfcs: [rfc(6672)],
  },
  CERT: {
    purpose:
      "Stores a certificate or a certificate revocation list in DNS, or a URL pointing at one.",
    rfcs: [rfc(4398)],
  },
  SMIMEA: {
    purpose:
      "Associates an S/MIME certificate with one email address so a sender can find and verify it — the DANE mechanism for mail, mirroring TLSA field for field.",
    rfcs: [rfc(8162)],
  },
  OPENPGPKEY: {
    purpose:
      "Publishes the OpenPGP public key for one email address, so a sender can find it without consulting a keyserver.",
    rfcs: [rfc(7929)],
  },
  CDNSKEY: {
    purpose:
      "The child zone's request to its parent: build the DS record from this key. It lets a zone roll its key-signing key without an out-of-band exchange with the registrar.",
    rfcs: [
      rfc(7344),
      rfc(8078, undefined, "Adds the initial-trust and removal cases."),
    ],
  },
  AFSDB: {
    purpose:
      "Points at the database servers for an AFS cell, or at a DCE authenticated-name server.",
    rfcs: [
      rfc(1183),
      rfc(
        5864,
        undefined,
        "Replaces AFSDB with SRV records for AFS service location.",
      ),
    ],
  },
  APL: {
    purpose:
      "Lists ranges of IP address prefixes attached to a name, each optionally negated. Experimental: the RFC defines the record and its format, but what a list means is left to the application reading it.",
    rfcs: [rfc(3123)],
  },
  DCHID: {
    purpose:
      "Lets a DHCP server prove it already owns a name before updating it, so two clients cannot fight over the same hostname. The content is an opaque digest the DHCP server generates. Listed here as DCHID, but the IANA type is DHCID.",
    rfcs: [rfc(4701)],
  },
  HIP: {
    purpose:
      "Publishes a host's Host Identity Protocol identity — a public key, with optional rendezvous servers — so peers can reach a host that is named by key rather than by address.",
    rfcs: [rfc(8005)],
  },
  IPSECKEY: {
    purpose:
      "Publishes an IPsec public key and gateway for a host or an address range, so a peer can set up IPsec without having the key configured in advance.",
    rfcs: [rfc(4025)],
  },
  NSEC: {
    purpose:
      "Proves that a name, or a type at a name, does not exist, by naming the next name in the zone's sorted order. Produced by the zone signer; it is not written by hand.",
    rfcs: [rfc(4034, "4")],
  },
  RRSIG: {
    purpose:
      "The DNSSEC signature over one record set, carrying its validity window and the key that made it. Produced by the zone signer; it is not written by hand.",
    rfcs: [rfc(4034, "3")],
  },
  SOA: {
    purpose:
      "Start of Authority: one per zone, holding the primary nameserver, the administrator's mailbox, the serial number secondaries watch for changes, and the timers that govern transfers and negative caching.",
    rfcs: [
      rfc(1035, "3.3.13"),
      rfc(
        2308,
        undefined,
        "Redefines the final field as the negative-caching TTL.",
      ),
    ],
  },
  SVCB: {
    purpose:
      "Service Binding: describes how to reach a service — an alternative endpoint, a port, which protocols it speaks — in a single lookup, instead of several round-trips of discovery.",
    rfcs: [rfc(9460)],
  },
  HTTPS: {
    purpose:
      "The HTTPS-specific form of SVCB. A browser learns ALPN support (so it can start on HTTP/3), a port, an alternative endpoint and address hints before it connects — and an apex name can point at another host, which a CNAME cannot do.",
    rfcs: [rfc(9460)],
  },
  URI: {
    purpose:
      "Maps a service name to a URI, for when the answer is a URL rather than the host and port an SRV record would give you.",
    rfcs: [rfc(7553)],
  },
  ALIAS: {
    purpose:
      "A provider-specific record, not an IANA type: it behaves like a CNAME but is legal at the zone apex, because the DNS provider resolves the target itself and serves the resulting addresses. Support and exact behaviour vary between providers.",
    rfcs: [],
  },
  ANAME: {
    purpose:
      "A provider-specific apex alias, equivalent to ALIAS at most providers that offer it. An IETF draft was proposed but never standardised, so behaviour is defined by your provider, not by a spec.",
    rfcs: [],
  },
};

/** Look up the purpose and specifications for a record type. */
export function getRecordDoc(type: string | undefined) {
  if (!type) return undefined;
  return RECORD_DOCS[type as RecordType];
}
