// Generated by npm run deps:manifest (scripts/generate-dependency-manifest.ts). Do not edit.
//
// Counts only, so a caller that just wants "45 of 712" — the diagnostics
// payload, the About header — can import them statically instead of loading
// the ~175 KB manifest. `test/dependencyManifest.contract.test.ts` derives
// these from the manifest and fails when this file disagrees.

/** How many packages this build is made of, by ecosystem. */
export const DEPENDENCY_TOTALS = {
  npm: { direct: 26, directDevelopment: 27, directOptional: 1, total: 565 },
  rust: { direct: 46, directDevelopment: 1, workspaceCrates: 20, total: 715 },
} as const;
